(function(){
  "use strict";
  const $=id=>document.getElementById(id);const state={parsed:null,sheet:null,mapping:{},normalized:null,records:[],filters:{},period:null,expanded:new Set(),statement:null,drill:{records:[],filtered:[],page:1,pageSize:25,title:""}};
  const els={landing:$("landing"),mappingView:$("mappingView"),reportView:$("reportView"),fileInput:$("fileInput"),dropZone:$("dropZone"),loader:$("loader"),loaderTitle:$("loaderTitle"),loaderDetail:$("loaderDetail"),loaderProgress:$("loaderProgress")};
  const stages=[["Reading workbook","Inspecting worksheets and columns",18],["Validating records","Checking amounts, dates and duplicate rows",38],["Building financial structure","Classifying accounts and preventing double counting",62],["Calculating profitability","Resolving periods and comparison basis",82],["Rendering analysis","Preparing the executive management view",96]];
  const classificationLabels=FinancialEngine.CATEGORIES;
  function show(view){[els.landing,els.mappingView,els.reportView].forEach(v=>v.hidden=v!==view);document.querySelectorAll(".report-only").forEach(el=>el.hidden=view!==els.reportView);$("fileContext").hidden=view===els.landing;window.scrollTo({top:0})}
  function setLoader(step=0){const [title,detail,p]=stages[step];els.loader.hidden=false;els.loaderTitle.textContent=title;els.loaderDetail.textContent=detail;els.loaderProgress.style.width=`${p}%`}
  function closeLoader(){els.loaderProgress.style.width="100%";setTimeout(()=>els.loader.hidden=true,170)}
  const wait=()=>new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,35)));
  async function handleFile(file){
    if(!file)return;try{setLoader(0);await wait();state.parsed=await ExcelParser.parse(file);state.sheet=bestSheet(state.parsed.sheets);setLoader(1);await wait();configureMapping(state.sheet);renderMapping();$("fileName").textContent=file.name;$("fileContext").hidden=false;closeLoader();show(els.mappingView)}catch(e){closeLoader();alert(e.message||"The workbook could not be processed.")}
  }
  function bestSheet(sheets){return sheets.filter(s=>s.headers.length).sort((a,b)=>((b.detection.accountName.score+b.detection.amount.score+b.periodColumns.length)-(a.detection.accountName.score+a.detection.amount.score+a.periodColumns.length)))[0]||sheets[0]}
  function configureMapping(sheet){const d=sheet.detection;state.mapping={accountCode:d.accountCode.score>=.7?d.accountCode.header:"",accountName:d.accountName.score>=.7?d.accountName.header:"",amount:sheet.periodColumns.length>=2?"":(d.amount.score>=.7?d.amount.header:""),date:d.date.score>=.7?d.date.header:"",category:d.category.score>=.85?d.category.header:"",department:d.department.score>=.85?d.department.header:"",costCenter:d.costCenter.score>=.85?d.costCenter.header:"",branch:d.branch.score>=.85?d.branch.header:"",businessUnit:d.businessUnit.score>=.85?d.businessUnit.header:"",currency:d.currency.score>=.85?d.currency.header:"",scenario:d.scenario.score>=.85?d.scenario.header:""}}
  function renderMapping(){
    const sheet=state.sheet;$("sheetSelect").innerHTML=state.parsed.sheets.map(s=>`<option value="${html(s.name)}" ${s.name===sheet.name?"selected":""}>${html(s.name)}</option>`).join("");
    $("mappingSummary").textContent=`${state.parsed.fileName} · ${state.parsed.sheets.length} worksheet${state.parsed.sheets.length===1?"":"s"} detected`;
    $("workbookStats").innerHTML=[["Rows",sheet.rows.length],["Columns",sheet.headers.length],["Period columns",sheet.periodColumns.length],["Worksheets",state.parsed.sheets.length]].map(([l,v])=>`<div class="stat-tile"><b>${v}</b><small>${l}</small></div>`).join("");
    const fields=[{key:"accountCode",label:"Account code",required:false},{key:"accountName",label:"Account name",required:true},{key:"amount",label:"Amount",required:sheet.periodColumns.length<2},{key:"date",label:"Date / period",required:false},{key:"category",label:"Classification"},{key:"department",label:"Department"},{key:"costCenter",label:"Cost center"},{key:"branch",label:"Branch"},{key:"businessUnit",label:"Business unit"},{key:"currency",label:"Currency"},{key:"scenario",label:"Scenario"}];
    $("mappingFields").innerHTML=fields.map(f=>{const detected=sheet.detection[f.key]?.score||0;const confidence=detected>=.9?"high":detected>=.7?"medium":"low";return`<label class="mapping-row"><span>${f.label}${f.required?` <i class="required">*</i>`:""}</span><select data-map="${f.key}"><option value="">Not mapped</option>${sheet.headers.map(h=>`<option value="${html(h)}" ${state.mapping[f.key]===h?"selected":""}>${html(h)}</option>`).join("")}</select><i class="confidence ${confidence}" title="${confidence} confidence"></i></label>`}).join("");
    document.querySelectorAll("[data-map]").forEach(select=>select.addEventListener("change",()=>{state.mapping[select.dataset.map]=select.value;previewQuality()}));previewQuality();
  }
  function previewQuality(){
    const sheet=state.sheet;let result;try{result=ExcelParser.normalize(sheet,state.mapping,{defaultYear:new Date().getFullYear()})}catch{return}const q=result.quality;
    $("qualityCards").innerHTML=[["Imported rows",q.total,""],["Normalized values",q.valid,"good"],["Excluded rows",q.excluded,q.excluded?"warn":"good"],["Warnings",q.warnings,q.warnings?"warn":"good"],["Duplicates",q.duplicates,q.duplicates?"warn":"good"]].map(([l,v,c])=>`<div class="quality-card ${c}"><b>${v}</b><small>${l}</small></div>`).join("");
    $("qualityIssues").innerHTML=(result.issues.length?result.issues:["No material structural issues detected in the preview."]).map(i=>`<li>${html(i)}</li>`).join("");
    const valid=Boolean(state.mapping.accountName||state.mapping.accountCode)&&Boolean(state.mapping.amount||sheet.periodColumns.length>=2);$("mappingConfidence").textContent=valid?"Ready":"Needs review";$("mappingConfidence").className=`badge ${valid?"":"bad"}`;$("buildReportBtn").disabled=!valid;
  }
  async function buildReport(){
    $("mappingError").textContent="";try{setLoader(1);await wait();state.normalized=ExcelParser.normalize(state.sheet,state.mapping,{defaultYear:new Date().getFullYear()});if(!state.normalized.records.length)throw new Error("No valid financial records remain. Review the account and amount mappings.");setLoader(2);await wait();state.records=FinancialEngine.prepare(state.normalized.records);state.normalized.quality.unmapped=new Set(state.records.filter(r=>r.category==="Unmapped").map(FinancialEngine.mappingKey)).size;const periods=FinancialEngine.periodSet(state.records);state.period=periods.at(-1);state.filters={};setLoader(3);await wait();renderFilterControls();populatePeriods();setLoader(4);await wait();renderAll();show(els.reportView);closeLoader()}catch(e){closeLoader();$("mappingError").textContent=e.message}
  }
  function populatePeriods(){const periods=FinancialEngine.periodSet(state.records);$("periodSelect").innerHTML=periods.map(p=>{const label=state.records.find(r=>r.period===p)?.periodLabel||p;return`<option value="${html(p)}" ${p===state.period?"selected":""}>${html(label)}</option>`}).join("")}
  function filteredBase(){return FilterEngine.apply(state.records,state.filters)}
  function periodData(period){return filteredBase().filter(r=>r.period===period)}
  function previousPeriod(){const periods=FinancialEngine.periodSet(filteredBase());const i=periods.indexOf(state.period);return i>0?periods[i-1]:null}
  function renderFilterControls(){
    const dimensions=FilterEngine.contextual(state.records,state.filters);$("filterControls").innerHTML=dimensions.map(d=>`<div class="filter-group"><label for="filter-${d.key}">${d.label}</label><select id="filter-${d.key}" data-filter="${d.key}"><option value="__all__">All ${d.label.toLowerCase()}s</option>${d.values.map(v=>`<option value="${html(v)}" ${state.filters[d.key]===v?"selected":""}>${html(v)}</option>`).join("")}</select></div>`).join("");
    document.querySelectorAll("[data-filter]").forEach(select=>select.addEventListener("change",()=>{state.filters[select.dataset.filter]=select.value;renderFilterControls();renderAll()}));const count=Object.values(state.filters).filter(v=>v&&v!=="__all__").length;$("filterCount").textContent=count;renderActiveFilters()
  }
  function renderActiveFilters(){const items=Object.entries(state.filters).filter(([,v])=>v&&v!=="__all__");$("activeFilters").innerHTML=items.map(([k,v])=>`<button class="filter-chip" data-remove-filter="${k}">${html(FilterEngine.labels[k])}: ${html(v)} ×</button>`).join("");document.querySelectorAll("[data-remove-filter]").forEach(b=>b.addEventListener("click",()=>{delete state.filters[b.dataset.removeFilter];renderFilterControls();renderAll()}))}
  function renderAll(){
    const previous=previousPeriod(),currentRecords=periodData(state.period),previousRecords=previous?periodData(previous):[];state.statement=FinancialEngine.buildStatement(currentRecords,previousRecords);const drivers=FinancialEngine.driverAnalysis(currentRecords,previousRecords);const labels={current:state.records.find(r=>r.period===state.period)?.periodLabel||state.period,previous:previous?(state.records.find(r=>r.period===previous)?.periodLabel||previous):"No prior period"};
    $("contextPeriod").textContent=labels.current;$("reportSubtitle").textContent=`${labels.current} · ${currentRecords.length} normalized financial records`;$("statementCaption").textContent=`${labels.current} versus ${labels.previous}`;$("comparisonBasis").textContent=previous?`${labels.current} versus ${labels.previous}`:"No earlier period is available";renderKPIs(state.statement,labels);renderStatement(state.statement);renderInsights(state.statement,drivers);renderDrivers(drivers);renderExpenseTable(state.statement);renderManager();renderCharts(filteredBase(),state.statement.currentMetrics);renderActiveFilters()
  }
  function renderKPIs(s,labels){const c=s.currentMetrics,p=s.previousMetrics;const candidates=c.hasRevenue?[["Revenue",c.revenue,p.revenue,1],["Gross Profit",c.gross,p.gross,1],["Operating Profit",c.operating,p.operating,1],["Net Profit",c.net,p.net,1],["Gross Margin",c.gross/c.revenue,p.revenue?p.gross/p.revenue:null,1,"pct"],["OPEX / Revenue",c.opex/c.revenue,p.revenue?p.opex/p.revenue:null,-1,"pct"]]:[["Operating Expenses",c.opex,p.opex,-1],["Total Expenses",c.expenseTotal,p.expenseTotal,-1],["Mapped P&L Accounts",s.currentAccounts.filter(a=>a.category!=="Unmapped").length,null,1,"count"],["Unmapped Accounts",s.currentAccounts.filter(a=>a.category==="Unmapped").length,null,-1,"count"]];
    $("kpiGrid").innerHTML=candidates.slice(0,4).map(([label,value,prev,direction,type])=>{const variance=prev===null?null:value-prev;const vp=prev?variance/Math.abs(prev):null;const status=vp===null?"neutral":variance*direction>=0?"good":"bad";return`<article class="kpi-card"><div class="label">${label}</div><div class="value">${type==="pct"?formatPct(value):type==="count"?value:formatMoney(value)}</div><div class="comparison"><span class="variance-tag ${status}">${vp===null?"No comparison":`${variance>=0?"↑":"↓"} ${formatPct(vp)}`}</span><span>${labels.previous}</span></div></article>`}).join("")
  }
  function renderStatement(statement){const scale=Number($("numberScale").value||1);const rows=[];statement.lines.forEach(line=>{const open=state.expanded.has(line.id);rows.push(`<tr class="${line.type}"><td><button class="line-toggle" data-toggle="${html(line.id)}" ${line.accounts.length?"":"disabled"}>${line.accounts.length?(open?"▾":"▸"):""} ${html(line.label)}</button></td>${numberCells(line,scale)}</tr>`);if(open)line.accounts.forEach(a=>rows.push(`<tr class="detail"><td class="indent-1"><button class="account-link" data-drill="${html(a.key)}">${html(a.accountCode)} · ${html(a.accountName)}</button></td>${numberCells({current:a.value,previous:a.previous,variance:a.value-a.previous,variancePct:a.previous?(a.value-a.previous)/Math.abs(a.previous):null,revenuePct:statement.currentMetrics.revenue?a.value/statement.currentMetrics.revenue:null,favorableDirection:line.favorableDirection},scale)}</tr>`))});$("statementBody").innerHTML=rows.join("");document.querySelectorAll("[data-toggle]").forEach(b=>b.addEventListener("click",()=>{state.expanded.has(b.dataset.toggle)?state.expanded.delete(b.dataset.toggle):state.expanded.add(b.dataset.toggle);renderStatement(state.statement)}));document.querySelectorAll("[data-drill]").forEach(b=>b.addEventListener("click",()=>openDrill(b.dataset.drill)));
    const balanceCount=new Set(periodData(state.period).filter(r=>r.category==="Balance Sheet").map(FinancialEngine.mappingKey)).size;const unmappedCount=new Set(periodData(state.period).filter(r=>r.category==="Unmapped").map(FinancialEngine.mappingKey)).size;const notice=$("statementNotice");if(!statement.currentMetrics.hasRevenue||balanceCount||unmappedCount){notice.hidden=false;notice.textContent=`Report safeguard: ${balanceCount} balance-sheet account(s) excluded; ${unmappedCount} account(s) remain unmapped. ${statement.currentMetrics.hasRevenue?"Profit lines use confirmed P&L classifications only.":"Revenue, gross profit, EBITDA and net profit are withheld because no revenue account is supported by the selected data."}`}else notice.hidden=true
  }
  function numberCells(line,scale){const favorable=line.variance*line.favorableDirection>=0?"favorable":"unfavorable";return`<td class="${line.current<0?"negative":""}">${formatMoney(line.current,scale)}</td><td class="${line.previous<0?"negative":""}">${formatMoney(line.previous,scale)}</td><td class="${favorable}">${formatMoney(line.variance,scale)}</td><td class="${favorable}">${formatPct(line.variancePct)}</td><td>${formatPct(line.revenuePct)}</td>`}
  function renderInsights(statement,drivers){const result=InsightEngine.generate(statement,drivers);$("attentionList").innerHTML=result.attention.length?result.attention.map(a=>`<div class="attention-item"><strong>${html(a.title)}</strong><span>${html(a.detail)}</span></div>`).join(""):`<div class="attention-item"><strong>No material alert</strong><span>No threshold-based management attention item was detected.</span></div>`;$("insightsList").innerHTML=result.insights.length?result.insights.map(i=>`<li>${html(i)}</li>`).join(""):`<li>More classified periods are required for comparative insight.</li>`}
  function renderDrivers(drivers){const pos=drivers.filter(d=>d.benefit>0).slice(0,5),neg=drivers.filter(d=>d.benefit<0).slice(0,5),max=Math.max(...drivers.map(d=>Math.abs(d.benefit)),1);const cards=(arr,negative=false)=>arr.length?arr.map(d=>`<div class="driver ${negative?"negative-driver":""}"><span class="driver-name">${html(d.accountName)}</span><span class="driver-value ${negative?"unfavorable":"favorable"}">${formatMoney(d.benefit)}</span><div class="driver-bar"><i style="width:${Math.max(4,Math.abs(d.benefit)/max*100)}%"></i></div></div>`).join(""):`<p class="muted">No material ${negative?"negative":"positive"} drivers.</p>`;$("positiveDrivers").innerHTML=cards(pos);$("negativeDrivers").innerHTML=cards(neg,true)}
  function renderExpenseTable(statement){const query=$("accountSearch").value.trim().toLowerCase();const accounts=statement.currentAccounts.filter(a=>FinancialEngine.expenseCategories.has(a.category)&&(`${a.accountCode} ${a.accountName} ${a.category}`).toLowerCase().includes(query)).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value));const total=statement.currentMetrics.expenseTotal;$("expenseBody").innerHTML=accounts.length?accounts.map(a=>`<tr><td><button class="account-link" data-drill="${html(a.key)}">${html(a.accountCode)} · ${html(a.accountName)}</button></td><td>${html(a.category)}</td><td>${formatMoney(a.value)}</td><td>${formatMoney(statement.previousMap.get(a.key)||0)}</td><td>${formatMoney(a.value-(statement.previousMap.get(a.key)||0))}</td><td>${formatPct(total?a.value/total:null)}</td></tr>`).join(""):`<tr><td colspan="6" class="muted">No matching expense accounts.</td></tr>`;document.querySelectorAll("#expenseBody [data-drill]").forEach(b=>b.addEventListener("click",()=>openDrill(b.dataset.drill)))}
  function renderManager(){const accounts=[...new Map(state.records.map(r=>[FinancialEngine.mappingKey(r),r])).values()].filter(r=>!$("unmappedOnly").checked||r.category==="Unmapped").sort((a,b)=>a.category.localeCompare(b.category)||a.accountName.localeCompare(b.accountName));$("mappingManagerBody").innerHTML=accounts.map(a=>`<tr><td>${html(a.accountCode)}</td><td>${html(a.accountName)}</td><td><select data-account-map="${html(FinancialEngine.mappingKey(a))}">${classificationLabels.map(c=>`<option ${a.category===c?"selected":""}>${c}</option>`).join("")}</select></td><td><span class="confidence-label ${a.confidence==="user"?"high":a.confidence}">${html(a.confidence)}</span></td></tr>`).join("")}
  function renderCharts(records,metrics){const available=["revenue","gross","ebitda","operating","net","opex"].filter(m=>m==="opex"||FinancialEngine.periodSet(records).some(p=>{const v=FinancialEngine.metrics(records.filter(r=>r.period===p))[m];return v!==null&&Math.abs(v)>.0001}));const selector=$("trendMetric");const old=selector.value;selector.innerHTML=available.map(m=>`<option value="${m}" ${old===m?"selected":""}>${ChartEngine.metricLabel(m)}</option>`).join("");ChartEngine.trend($("trendChart"),records,selector.value||available[0]||"opex");ChartEngine.expense($("expenseChart"),metrics);ChartEngine.waterfall($("waterfallChart"),metrics)}
  function openDrill(key){const account=state.statement.currentAccounts.find(a=>a.key===key);if(!account)return;state.drill={records:account.records,filtered:account.records,page:1,pageSize:25,title:account.accountName};$("drillTitle").textContent=account.accountName;$("drillMeta").textContent=`${account.accountCode} · ${account.category} · ${account.records.length} contributing record(s)`;$("drillSearch").value="";renderDrill();$("drillDialog").showModal()}
  function renderDrill(){const d=state.drill,headers=d.records[0]?Object.keys(d.records[0].source).filter(h=>h!=="__row"):[];const start=(d.page-1)*d.pageSize,rows=d.filtered.slice(start,start+d.pageSize);$("drillHead").innerHTML=`<tr>${headers.map(h=>`<th>${html(h)}</th>`).join("")}</tr>`;$("drillBody").innerHTML=rows.map(r=>`<tr>${headers.map(h=>`<td>${html(r.source[h]??"")}</td>`).join("")}</tr>`).join("");const pages=Math.max(1,Math.ceil(d.filtered.length/d.pageSize));$("pageStatus").textContent=`Page ${d.page} of ${pages}`;$("prevPage").disabled=d.page<=1;$("nextPage").disabled=d.page>=pages}
  function formatMoney(value,scale=Number($("numberScale")?.value||1)){if(value===null||value===undefined)return"—";const n=value/scale;const formatted=new Intl.NumberFormat("en",{minimumFractionDigits:0,maximumFractionDigits:scale===1?2:1}).format(Math.abs(n));return n<0?`(${formatted})`:formatted}
  function formatPct(value){if(value===null||value===undefined||!Number.isFinite(value))return"—";return`${(value*100).toFixed(1)}%`}
  function html(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
  function reset(){state.parsed=null;state.sheet=null;state.normalized=null;state.records=[];state.filters={};state.expanded.clear();els.fileInput.value="";show(els.landing)}
  $("browseBtn").addEventListener("click",e=>{e.stopPropagation();els.fileInput.click()});els.dropZone.addEventListener("click",()=>els.fileInput.click());els.dropZone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();els.fileInput.click()}});els.fileInput.addEventListener("change",()=>handleFile(els.fileInput.files[0]));["dragenter","dragover"].forEach(type=>els.dropZone.addEventListener(type,e=>{e.preventDefault();els.dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(type=>els.dropZone.addEventListener(type,e=>{e.preventDefault();els.dropZone.classList.remove("dragging")}));els.dropZone.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
  $("sheetSelect").addEventListener("change",()=>{state.sheet=state.parsed.sheets.find(s=>s.name===$("sheetSelect").value);configureMapping(state.sheet);renderMapping()});$("cancelMapping").addEventListener("click",reset);$("buildReportBtn").addEventListener("click",buildReport);$("newFileBtn").addEventListener("click",reset);$("periodSelect").addEventListener("change",()=>{state.period=$("periodSelect").value;renderAll()});$("numberScale").addEventListener("change",()=>renderStatement(state.statement));$("expandAll").addEventListener("click",()=>{const ids=state.statement.lines.filter(l=>l.accounts.length).map(l=>l.id);const all=ids.every(id=>state.expanded.has(id));state.expanded=all?new Set():new Set(ids);$("expandAll").textContent=all?"Expand all":"Collapse all";renderStatement(state.statement)});$("trendMetric").addEventListener("change",()=>ChartEngine.trend($("trendChart"),filteredBase(),$("trendMetric").value));$("accountSearch").addEventListener("input",()=>renderExpenseTable(state.statement));$("unmappedOnly").addEventListener("change",renderManager);$("applyMappings").addEventListener("click",()=>{document.querySelectorAll("[data-account-map]").forEach(s=>FinancialEngine.saveMapping(s.dataset.accountMap,s.value));state.records=FinancialEngine.prepare(state.normalized.records);renderFilterControls();renderAll()});$("resetFilters").addEventListener("click",()=>{state.filters={};renderFilterControls();renderAll()});$("openFilters").addEventListener("click",()=>$("filterDrawer").classList.add("open"));$("closeFilters").addEventListener("click",()=>$("filterDrawer").classList.remove("open"));$("exportBtn").addEventListener("click",()=>{const prev=previousPeriod();ExportEngine.statement(state.statement.lines,state.period,prev||"No prior period")});$("printBtn").addEventListener("click",()=>window.print());$("closeDrill").addEventListener("click",()=>$("drillDialog").close());$("drillSearch").addEventListener("input",()=>{const q=$("drillSearch").value.toLowerCase();state.drill.filtered=state.drill.records.filter(r=>JSON.stringify(r.source).toLowerCase().includes(q));state.drill.page=1;renderDrill()});$("drillExport").addEventListener("click",()=>ExportEngine.records(state.drill.filtered,`${state.drill.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-detail.csv`));$("prevPage").addEventListener("click",()=>{state.drill.page--;renderDrill()});$("nextPage").addEventListener("click",()=>{state.drill.page++;renderDrill()});
})();
