(function(){
  "use strict";
  const charts={};const palette={ink:"#252a2d",gold:"#b38a50",emerald:"#28725a",ruby:"#9a4747",slate:"#64727b",paper:"#ece8de"};
  function destroy(name){if(charts[name]){charts[name].destroy();delete charts[name]}}
  function baseOptions(){return{responsive:true,maintainAspectRatio:false,animation:{duration:280},plugins:{legend:{labels:{color:palette.slate,boxWidth:9,boxHeight:9,font:{family:"IBM Plex Sans",size:10}}},tooltip:{backgroundColor:palette.ink,padding:10,callbacks:{label:c=>`${c.dataset.label?`${c.dataset.label}: `:""}${new Intl.NumberFormat("en",{maximumFractionDigits:1}).format(c.raw)}`}}},scales:{x:{grid:{display:false},ticks:{color:palette.slate,font:{size:10}}},y:{grid:{color:"rgba(100,114,123,.12)"},ticks:{color:palette.slate,font:{size:10},callback:v=>Intl.NumberFormat("en",{notation:"compact"}).format(v)}}}}}
  function toggleEmpty(canvas,empty){canvas.hidden=empty;const el=canvas.parentElement.querySelector(".chart-empty");if(el)el.hidden=!empty}
  function trend(canvas,records,metric){destroy("trend");const periods=FinancialEngine.periodSet(records);const data=periods.map(period=>FinancialEngine.metrics(records.filter(r=>r.period===period))[metric]);toggleEmpty(canvas,periods.length<2||data.every(v=>v===null));if(periods.length<2)return;charts.trend=new Chart(canvas,{type:"line",data:{labels:periods.map(p=>records.find(r=>r.period===p)?.periodLabel||p),datasets:[{label:metricLabel(metric),data,borderColor:palette.gold,backgroundColor:"rgba(179,138,80,.12)",fill:true,tension:.28,pointBackgroundColor:palette.ink,pointRadius:3}]},options:baseOptions()})}
  function expense(canvas,metrics){destroy("expense");const entries=[...metrics.categoryTotals].filter(([k,v])=>FinancialEngine.expenseCategories.has(k)&&Math.abs(v)>.0001).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,7);toggleEmpty(canvas,!entries.length);if(!entries.length)return;const options=baseOptions();options.plugins.legend.position="bottom";delete options.scales;charts.expense=new Chart(canvas,{type:"doughnut",data:{labels:entries.map(e=>window.I18n?.t(e[0])||e[0]),datasets:[{data:entries.map(e=>Math.abs(e[1])),backgroundColor:[palette.ink,palette.gold,palette.slate,"#8b6f61","#506e62","#8e854d","#7a6978"],borderColor:"#fffdf8",borderWidth:3}]},options:{...options,cutout:"68%"}})}
  function waterfall(canvas,metrics){destroy("waterfall");if(!metrics.hasRevenue){toggleEmpty(canvas,true);return}toggleEmpty(canvas,false);const labels=["Revenue","COGS","Gross profit","OPEX",metrics.ebitda!==null?"EBITDA":"Operating profit","Other / finance","Tax","Net profit"];
    const vals=[metrics.revenue,-metrics.cogs,metrics.gross,-metrics.opex,metrics.ebitda??metrics.operating,(metrics.otherIncome+metrics.other+metrics.fx-metrics.finance),-metrics.tax,metrics.net];
    const floating=[];let running=0;vals.forEach((v,i)=>{if([0,2,4,7].includes(i)){floating.push([0,v]);running=v}else{floating.push([running,running+v]);running+=v}});const options=baseOptions();options.plugins.legend.display=false;options.scales.x.stacked=false;charts.waterfall=new Chart(canvas,{type:"bar",data:{labels,datasets:[{data:floating,backgroundColor:vals.map((v,i)=>[0,2,4,7].includes(i)?palette.ink:(v>=0?palette.emerald:palette.ruby)),borderRadius:2}]},options})}
  function metricLabel(metric){const label=({revenue:"Revenue",gross:"Gross Profit",ebitda:"EBITDA",operating:"Operating Profit",net:"Net Profit",opex:"Operating Expenses"})[metric]||metric;return window.I18n?.t(label)||label}
  window.ChartEngine={trend,expense,waterfall,metricLabel};
})();
