(function(){
  "use strict";
  const ar={
    "Income Statement Intelligence":"ذكاء قائمة الدخل","Skip to report":"الانتقال إلى التقرير","Workbook":"ملف العمل","Download template":"تنزيل القالب","Filters":"الفلاتر","New file":"ملف جديد","Export CSV":"تصدير CSV","Print / PDF":"طباعة / PDF",
    "Financial reporting, resolved":"تقارير مالية واضحة","Turn accounting data into a decision-ready income statement.":"حوّل البيانات المحاسبية إلى قائمة دخل جاهزة لاتخاذ القرار.","Upload a financial workbook to build an executive P&L, trace movements, test classifications, and focus management attention.":"ارفع ملفًا ماليًا لبناء قائمة دخل تنفيذية، وتتبع التغيرات، ومراجعة التصنيفات، وتحديد أولويات الإدارة.","Private by design.":"خصوصية من أساس التصميم.","Financial files are processed locally in your browser and never uploaded to a server.":"تتم معالجة الملفات المالية محليًا داخل متصفحك ولا تُرفع إلى أي خادم.",
    "Upload financial workbook":"رفع ملف مالي","Drop an Excel or CSV file here":"اسحب ملف Excel أو CSV إلى هنا","Choose file":"اختيار ملف","XLSX, XLS or CSV · processed on this device":"XLSX أو XLS أو CSV · تتم المعالجة على هذا الجهاز","Adaptive mapping":"مطابقة مرنة","Finds accounts, amounts, periods, budgets and business dimensions.":"يتعرف على الحسابات والمبالغ والفترات والموازنات والأبعاد التنظيمية.","Financial control":"ضبط مالي","Excludes likely balance-sheet and source subtotal rows before aggregation.":"يستبعد حسابات الميزانية والمجاميع المصدرية المحتملة قبل التجميع.","Management signal":"إشارة إدارية","Surfaces material drivers, margin changes and investigation priorities.":"يُظهر المحركات الجوهرية وتغيرات الهوامش وأولويات المراجعة.",
    "Import review":"مراجعة الاستيراد","Confirm the financial structure":"تأكيد الهيكل المالي","Review detected fields before the report is calculated.":"راجع الحقول المكتشفة قبل احتساب التقرير.","Cancel":"إلغاء","Worksheet":"ورقة العمل","Select the table containing financial data.":"اختر الجدول الذي يحتوي البيانات المالية.","Data worksheet":"ورقة البيانات","Column mapping":"مطابقة الأعمدة","Required fields are marked. Uncertain detection always needs confirmation.":"الحقول الإلزامية محددة، وأي اكتشاف غير مؤكد يحتاج مراجعة.","Review":"مراجعة","Data quality":"جودة البيانات","Nothing is silently discarded.":"لا يتم تجاهل أي سجل دون توضيح.","Build income statement":"إنشاء قائمة الدخل","Rows":"الصفوف","Columns":"الأعمدة","Period columns":"أعمدة الفترات","Worksheets":"أوراق العمل","Amount":"المبلغ","Date / period":"التاريخ / الفترة","Department":"القسم","Cost center":"مركز التكلفة","Branch":"الفرع","Business unit":"وحدة الأعمال","Currency":"العملة","Scenario":"السيناريو","Not mapped":"غير مطابق","Imported rows":"الصفوف المستوردة","Normalized values":"القيم المعالجة","Excluded rows":"الصفوف المستبعدة","Warnings":"التحذيرات","Duplicates":"المكررات","Ready":"جاهز","Needs review":"يحتاج مراجعة","No material structural issues detected in the preview.":"لم يتم اكتشاف مشاكل هيكلية جوهرية في المعاينة.",
    "Report controls":"عناصر التحكم","Reset filters":"إعادة ضبط الفلاتر","Comparison basis":"أساس المقارنة","Executive performance brief":"ملخص الأداء التنفيذي","Income Statement":"قائمة الدخل","Filtered management view":"عرض إداري مفلتر","Reporting period":"الفترة المالية","Core report":"التقرير الأساسي","Statement of performance":"بيان الأداء","Current period versus previous period":"الفترة الحالية مقابل الفترة السابقة","Numbers":"الأرقام","Actual":"فعلي","Thousands":"آلاف","Millions":"ملايين","Expand all":"توسيع الكل","Collapse all":"طي الكل","Financial line":"البند المالي","Current":"الحالي","Previous":"السابق","Variance":"الانحراف","Variance %":"الانحراف %","% Revenue":"% من الإيراد",
    "Decision support":"دعم القرار","Management attention":"اهتمام الإدارة","Analytical observations":"ملاحظات تحليلية","Movement":"الحركة","Profitability trend":"اتجاه الربحية","Cost structure":"هيكل التكلفة","Expense composition":"توزيع المصروفات","Profit bridge":"جسر الربحية","Waterfall":"الشلال المالي","No period trend available":"لا يتوفر اتجاه زمني","No expense data available":"لا تتوفر بيانات مصروفات","Revenue and profit lines are not supported by the current data":"بيانات الإيرادات والأرباح غير مدعومة في الملف الحالي","Variance contribution":"مساهمة الانحراف","Top positive drivers":"أهم المحركات الإيجابية","Top negative drivers":"أهم المحركات السلبية","Materiality view":"تحليل الأهمية النسبية","Expense analysis":"تحليل المصروفات","Ranked by current-period operating expense.":"مرتبة حسب مصروف الفترة الحالية.","Account":"الحساب","Classification":"التصنيف","% OPEX":"% من المصروفات التشغيلية","Financial governance":"الحوكمة المالية","Account classification manager":"مدير تصنيف الحسابات","Review inferred classifications. Changes are saved on this device.":"راجع التصنيفات المقترحة. تُحفظ التغييرات على هذا الجهاز.","Unmapped only":"غير المصنف فقط","Apply changes":"تطبيق التغييرات","Account code":"رقم الحساب","Account name":"اسم الحساب","Detected classification":"التصنيف المكتشف","Confidence":"الثقة",
    "Reading workbook":"قراءة ملف العمل","Inspecting worksheets and columns":"فحص أوراق العمل والأعمدة","Validating records":"التحقق من السجلات","Checking amounts, dates and duplicate rows":"فحص المبالغ والتواريخ والسجلات المكررة","Building financial structure":"بناء الهيكل المالي","Classifying accounts and preventing double counting":"تصنيف الحسابات ومنع الازدواجية","Calculating profitability":"احتساب الربحية","Resolving periods and comparison basis":"تحديد الفترات وأساس المقارنة","Rendering analysis":"عرض التحليل","Preparing the executive management view":"تجهيز العرض التنفيذي","Source records":"السجلات المصدرية","Account detail":"تفاصيل الحساب","Export records":"تصدير السجلات","Previous":"السابق","Next":"التالي","Built by":"بواسطة","Learn. Analyse. Lead.":"تعلّم. حلّل. قُد.",
    "Revenue":"الإيرادات","Contra Revenue":"مردودات وخصومات الإيرادات","COGS":"تكلفة المبيعات","Selling Expense":"مصاريف البيع","Marketing Expense":"مصاريف التسويق","Administrative Expense":"المصاريف الإدارية","Payroll":"الرواتب والموظفين","Depreciation & Amortization":"الاستهلاك والإطفاء","Other Operating Expense":"مصاريف تشغيلية أخرى","Other Income":"إيرادات أخرى","Finance Cost":"تكاليف التمويل","FX Gain / Loss":"أرباح / خسائر العملة","Tax":"الضرائب","Other":"أخرى","Balance Sheet":"الميزانية العمومية","Unmapped":"غير مصنف","Net Revenue":"صافي الإيرادات","Gross Profit":"مجمل الربح","Operating expenses":"المصاريف التشغيلية","Total Operating Expenses":"إجمالي المصاريف التشغيلية","Operating Profit / EBIT":"الربح التشغيلي / EBIT","Finance costs":"تكاليف التمويل","Profit Before Tax":"الربح قبل الضريبة","Income tax":"ضريبة الدخل","Net Profit":"صافي الربح","Total Expenses":"إجمالي المصروفات","Mapped P&L Accounts":"حسابات قائمة الدخل المصنفة","Unmapped Accounts":"الحسابات غير المصنفة","Operating Expenses":"المصاريف التشغيلية","Gross Margin":"هامش مجمل الربح","OPEX / Revenue":"المصاريف التشغيلية / الإيرادات","No comparison":"لا توجد مقارنة","No prior period":"لا توجد فترة سابقة","No material alert":"لا يوجد تنبيه جوهري","No threshold-based management attention item was detected.":"لم يتم اكتشاف بند يتجاوز حدود اهتمام الإدارة.","More classified periods are required for comparative insight.":"يلزم توفر فترات مصنفة إضافية لإنتاج تحليل مقارن.","No matching expense accounts.":"لا توجد حسابات مصروفات مطابقة.","No material positive drivers.":"لا توجد محركات إيجابية جوهرية.","No material negative drivers.":"لا توجد محركات سلبية جوهرية.","All periods":"جميع الفترات","All departments":"جميع الأقسام","All cost centers":"جميع مراكز التكلفة","All branchs":"جميع الفروع","All business units":"جميع وحدات الأعمال","All currencys":"جميع العملات","All scenarios":"جميع السيناريوهات"
  };
  let lang=localStorage.getItem("lucent-language")||"en";
  const reverse=Object.fromEntries(Object.entries(ar).map(([en,val])=>[val,en]));
  function t(value){const s=String(value??"");return lang==="ar"?(ar[s]||s):(reverse[s]||s)}
  function translateNode(node){if(node.nodeType===3){const raw=node.nodeValue;const trimmed=raw.trim();if(!trimmed)return;const translated=t(trimmed);if(translated!==trimmed)node.nodeValue=raw.replace(trimmed,translated)}else if(node.nodeType===1){["placeholder","aria-label","title"].forEach(attr=>{if(node.hasAttribute(attr)){const original=node.dataset[`i18n${attr.replace(/-./g,m=>m[1].toUpperCase())}`]||node.getAttribute(attr);node.dataset[`i18n${attr.replace(/-./g,m=>m[1].toUpperCase())}`]=original;node.setAttribute(attr,lang==="ar"?(ar[original]||original):original)}})}}
  function apply(root=document){root.querySelectorAll("*").forEach(el=>{translateNode(el);el.childNodes.forEach(n=>{if(n.nodeType===3)translateNode(n)})});document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.body.classList.toggle("rtl",lang==="ar");const toggle=document.getElementById("languageToggle");if(toggle)toggle.textContent=lang==="ar"?"EN":"AR"}
  function set(next){lang=next;localStorage.setItem("lucent-language",lang);apply();document.dispatchEvent(new CustomEvent("languagechange",{detail:{lang}}))}
  function toggle(){set(lang==="en"?"ar":"en")}
  function current(){return lang}
  window.I18n={t,apply,set,toggle,current};
})();
